
server:
  port: 7000

spring:
  jackson:
    serialization-inclusion: non_null
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  jpa:
    hibernate.ddl-auto: update
    properties:
      javax.persistence.sharedCache.mode: ALL
      #hibernate.cache.use_second_level_cache: true
      #hibernate.cache.use_query_cache: true
      #hibernate.cache.region.factory_class: com.github.zhangyanwei.hibernate.cache.redis.RedisRegionFactory
  redis:
    host: 192.168.3.134
    port: 6379
  data:
    mongodb:
      host: 192.168.3.134
      port: 27017
      database: sct
  datasource:
    #platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.3.134:5433/sct
    username: yijubao
    password: yijubao.net@KjfbUkh981